name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Validar sintaxe do script
        run: |
          echo "::group::Validação de sintaxe"
          if [[ ! -f "status-check.sh" ]]; then
            echo "::error::Arquivo status-check.sh não encontrado!"
            exit 1
          fi
          bash -n status-check.sh
          echo "::endgroup::"
          echo "::warning::Validação concluída sem erros críticos."

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Executar testes simulados
        run: |
          echo "Running tests"
          echo "::notice::Testes executados com sucesso"
          exit 0

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Criar artefato
        run: |
          mkdir -p report
          echo "Simulação de relatório de testes." > report/test-report.txt
          cp status-check.sh report/
          zip -r report.zip report/
          echo "::notice::Artefato criado com sucesso."

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip

      - name: Resumo do Job
        run: |
          echo "### ✅ CI Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Sistema:** $RUNNER_OS" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Artefato:** [report.zip](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY

env:
  ACTIONS_STEP_DEBUG: true
