name: Run Monitor Contexts

on:
  workflow_dispatch:

jobs:
  use-env:
    runs-on: ubuntu-latest
    env:
      APP_ENV: dev  # Valor fixo para evitar erro de contexto
    steps:
      - name: Mostrar variável de ambiente
        run: echo "Ambiente: $APP_ENV"

  use-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar variável SUPPORT_EMAIL via vars
        run: echo "Email de suporte: ${{ vars.SUPPORT_EMAIL }}"

  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Usar API_KEY secreta
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo "Chave da API recebida com segurança."
``
